spring.application.name=pacemaker
server.port=8080

# datasource ######################################################################################
spring.datasource.hikari.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.hikari.jdbc-url=${PACEMAKER_JDBC_URL}
spring.datasource.hikari.username=${PACEMAKER_MYSQL_USERNAME}
spring.datasource.hikari.password=${PACEMAKER_MYSQL_PASSWORD}
##################################################################################################

# jpa ######################################################################################
# spring.jpa.hibernate.ddl-auto
# create: 기존 테이블을 삭제하고 새로 생성 (DROP - CREATE)
# create-drop: create와 동일하나 어플리케이션 종료시 테이블 삭제 (DROP - CREATE - DROP)
# update: 데이터베이스 테이블 - 엔터티 매핑정보를 비교해서 변경사항만 수정
# validate: 데이터베이스 테이블 - 엔터티 매핑정보를 비교해서 차이가있으면 어플리케이션을 실행하지 않음
# none: 자동 생성 기능을 사용하지 않음
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Seoul
# SQL 쿼리 리포트 설정 # System.out.print와 같음
#spring.jpa.show-sql=true
# 쿼리 출력 형식
spring.jpa.properties.hibernate.format_sql=true
# MySQL 8.x 사용 시 적용할 dialect 설정 (방언)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
# Hibernate SQL 및 쿼리 리포트 설정 (선택 사항)
# SQL 쿼리를 디버깅할 때 쿼리 리포트를 출력
logging.level.org.hibernate.SQL=debug
############################################################################################

# Mattermost #######################################################################
notification.mattermost.enabled=true
notification.mattermost.webhook-url=${PACEMAKER_NOTIFICATION_MATTERMOST_WEBHOOK_URL}
#notification.mattermost.channel=
#notification.mattermost.pretext=
#notification.mattermost.color=
#notification.mattermost.author-name=
#notification.mattermost.author-icon=
#notification.mattermost.title=
#notification.mattermost.text=
#notification.mattermost.footer=
############################################################################################

# OpenAI API #######################################################################
openai.api.key=${PACEMAKER_OPENAI_API_KEY}
####################################################################################

# GPU Server #######################################################################
gpu.server.url=${PACEMAKER_GPU_SERVER_URL}
####################################################################################

# Spring Batch #####################################################################
# 스프링 배치 테이블 자동 생성
spring.batch.jdbc.initialize-schema=always
# 서버 실행시 job에 등록된 작업 실행 설정 (false -> disabled)
spring.batch.job.enabled=false
####################################################################################
